// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: track_descriptor.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace UnityPerfetto.Protos {

  /// <summary>Holder for reflection information generated from track_descriptor.proto</summary>
  public static partial class TrackDescriptorReflection {

    #region Descriptor
    /// <summary>File descriptor for track_descriptor.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TrackDescriptorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZ0cmFja19kZXNjcmlwdG9yLnByb3RvEhV1bml0eV9wZXJmZXR0by5wcm90",
            "b3MaGHByb2Nlc3NfZGVzY3JpcHRvci5wcm90bxoXdGhyZWFkX2Rlc2NyaXB0",
            "b3IucHJvdG8aGGNvdW50ZXJfZGVzY3JpcHRvci5wcm90byLUAgoPVHJhY2tE",
            "ZXNjcmlwdG9yEhEKBHV1aWQYASABKARIAIgBARIYCgtwYXJlbnRfdXVpZBgF",
            "IAEoBEgBiAEBEhEKBG5hbWUYAiABKAlIAogBARI+Cgdwcm9jZXNzGAMgASgL",
            "MigudW5pdHlfcGVyZmV0dG8ucHJvdG9zLlByb2Nlc3NEZXNjcmlwdG9ySAOI",
            "AQESPAoGdGhyZWFkGAQgASgLMicudW5pdHlfcGVyZmV0dG8ucHJvdG9zLlRo",
            "cmVhZERlc2NyaXB0b3JIBIgBARI+Cgdjb3VudGVyGAggASgLMigudW5pdHlf",
            "cGVyZmV0dG8ucHJvdG9zLkNvdW50ZXJEZXNjcmlwdG9ySAWIAQFCBwoFX3V1",
            "aWRCDgoMX3BhcmVudF91dWlkQgcKBV9uYW1lQgoKCF9wcm9jZXNzQgkKB190",
            "aHJlYWRCCgoIX2NvdW50ZXJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::UnityPerfetto.Protos.ProcessDescriptorReflection.Descriptor, global::UnityPerfetto.Protos.ThreadDescriptorReflection.Descriptor, global::UnityPerfetto.Protos.CounterDescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::UnityPerfetto.Protos.TrackDescriptor), global::UnityPerfetto.Protos.TrackDescriptor.Parser, new[]{ "Uuid", "ParentUuid", "Name", "Process", "Thread", "Counter" }, new[]{ "Uuid", "ParentUuid", "Name", "Process", "Thread", "Counter" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TrackDescriptor : pb::IMessage<TrackDescriptor>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TrackDescriptor> _parser = new pb::MessageParser<TrackDescriptor>(() => new TrackDescriptor());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TrackDescriptor> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UnityPerfetto.Protos.TrackDescriptorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrackDescriptor() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrackDescriptor(TrackDescriptor other) : this() {
      _hasBits0 = other._hasBits0;
      uuid_ = other.uuid_;
      parentUuid_ = other.parentUuid_;
      name_ = other.name_;
      process_ = other.process_ != null ? other.process_.Clone() : null;
      thread_ = other.thread_ != null ? other.thread_.Clone() : null;
      counter_ = other.counter_ != null ? other.counter_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrackDescriptor Clone() {
      return new TrackDescriptor(this);
    }

    /// <summary>Field number for the "uuid" field.</summary>
    public const int UuidFieldNumber = 1;
    private readonly static ulong UuidDefaultValue = 0UL;

    private ulong uuid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Uuid {
      get { if ((_hasBits0 & 1) != 0) { return uuid_; } else { return UuidDefaultValue; } }
      set {
        _hasBits0 |= 1;
        uuid_ = value;
      }
    }
    /// <summary>Gets whether the "uuid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUuid {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "uuid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUuid() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "parent_uuid" field.</summary>
    public const int ParentUuidFieldNumber = 5;
    private readonly static ulong ParentUuidDefaultValue = 0UL;

    private ulong parentUuid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ParentUuid {
      get { if ((_hasBits0 & 2) != 0) { return parentUuid_; } else { return ParentUuidDefaultValue; } }
      set {
        _hasBits0 |= 2;
        parentUuid_ = value;
      }
    }
    /// <summary>Gets whether the "parent_uuid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasParentUuid {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "parent_uuid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearParentUuid() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private readonly static string NameDefaultValue = "";

    private string name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_ ?? NameDefaultValue; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearName() {
      name_ = null;
    }

    /// <summary>Field number for the "process" field.</summary>
    public const int ProcessFieldNumber = 3;
    private global::UnityPerfetto.Protos.ProcessDescriptor process_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::UnityPerfetto.Protos.ProcessDescriptor Process {
      get { return process_; }
      set {
        process_ = value;
      }
    }

    /// <summary>Field number for the "thread" field.</summary>
    public const int ThreadFieldNumber = 4;
    private global::UnityPerfetto.Protos.ThreadDescriptor thread_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::UnityPerfetto.Protos.ThreadDescriptor Thread {
      get { return thread_; }
      set {
        thread_ = value;
      }
    }

    /// <summary>Field number for the "counter" field.</summary>
    public const int CounterFieldNumber = 8;
    private global::UnityPerfetto.Protos.CounterDescriptor counter_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::UnityPerfetto.Protos.CounterDescriptor Counter {
      get { return counter_; }
      set {
        counter_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TrackDescriptor);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TrackDescriptor other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Uuid != other.Uuid) return false;
      if (ParentUuid != other.ParentUuid) return false;
      if (Name != other.Name) return false;
      if (!object.Equals(Process, other.Process)) return false;
      if (!object.Equals(Thread, other.Thread)) return false;
      if (!object.Equals(Counter, other.Counter)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasUuid) hash ^= Uuid.GetHashCode();
      if (HasParentUuid) hash ^= ParentUuid.GetHashCode();
      if (HasName) hash ^= Name.GetHashCode();
      if (process_ != null) hash ^= Process.GetHashCode();
      if (thread_ != null) hash ^= Thread.GetHashCode();
      if (counter_ != null) hash ^= Counter.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasUuid) {
        output.WriteRawTag(8);
        output.WriteUInt64(Uuid);
      }
      if (HasName) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (process_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Process);
      }
      if (thread_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Thread);
      }
      if (HasParentUuid) {
        output.WriteRawTag(40);
        output.WriteUInt64(ParentUuid);
      }
      if (counter_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Counter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasUuid) {
        output.WriteRawTag(8);
        output.WriteUInt64(Uuid);
      }
      if (HasName) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (process_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Process);
      }
      if (thread_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Thread);
      }
      if (HasParentUuid) {
        output.WriteRawTag(40);
        output.WriteUInt64(ParentUuid);
      }
      if (counter_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Counter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasUuid) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Uuid);
      }
      if (HasParentUuid) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ParentUuid);
      }
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (process_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Process);
      }
      if (thread_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Thread);
      }
      if (counter_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Counter);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TrackDescriptor other) {
      if (other == null) {
        return;
      }
      if (other.HasUuid) {
        Uuid = other.Uuid;
      }
      if (other.HasParentUuid) {
        ParentUuid = other.ParentUuid;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.process_ != null) {
        if (process_ == null) {
          Process = new global::UnityPerfetto.Protos.ProcessDescriptor();
        }
        Process.MergeFrom(other.Process);
      }
      if (other.thread_ != null) {
        if (thread_ == null) {
          Thread = new global::UnityPerfetto.Protos.ThreadDescriptor();
        }
        Thread.MergeFrom(other.Thread);
      }
      if (other.counter_ != null) {
        if (counter_ == null) {
          Counter = new global::UnityPerfetto.Protos.CounterDescriptor();
        }
        Counter.MergeFrom(other.Counter);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Uuid = input.ReadUInt64();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            if (process_ == null) {
              Process = new global::UnityPerfetto.Protos.ProcessDescriptor();
            }
            input.ReadMessage(Process);
            break;
          }
          case 34: {
            if (thread_ == null) {
              Thread = new global::UnityPerfetto.Protos.ThreadDescriptor();
            }
            input.ReadMessage(Thread);
            break;
          }
          case 40: {
            ParentUuid = input.ReadUInt64();
            break;
          }
          case 66: {
            if (counter_ == null) {
              Counter = new global::UnityPerfetto.Protos.CounterDescriptor();
            }
            input.ReadMessage(Counter);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Uuid = input.ReadUInt64();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            if (process_ == null) {
              Process = new global::UnityPerfetto.Protos.ProcessDescriptor();
            }
            input.ReadMessage(Process);
            break;
          }
          case 34: {
            if (thread_ == null) {
              Thread = new global::UnityPerfetto.Protos.ThreadDescriptor();
            }
            input.ReadMessage(Thread);
            break;
          }
          case 40: {
            ParentUuid = input.ReadUInt64();
            break;
          }
          case 66: {
            if (counter_ == null) {
              Counter = new global::UnityPerfetto.Protos.CounterDescriptor();
            }
            input.ReadMessage(Counter);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
