// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: trace_packet.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace UnityPerfetto.Protos {

  /// <summary>Holder for reflection information generated from trace_packet.proto</summary>
  public static partial class TracePacketReflection {

    #region Descriptor
    /// <summary>File descriptor for trace_packet.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TracePacketReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJ0cmFjZV9wYWNrZXQucHJvdG8SFXVuaXR5X3BlcmZldHRvLnByb3RvcxoR",
            "dHJhY2tfZXZlbnQucHJvdG8aFnRyYWNrX2Rlc2NyaXB0b3IucHJvdG8ihgIK",
            "C1RyYWNlUGFja2V0EhYKCXRpbWVzdGFtcBgIIAEoBEgCiAEBEkIKEHRyYWNr",
            "X2Rlc2NyaXB0b3IYPCABKAsyJi51bml0eV9wZXJmZXR0by5wcm90b3MuVHJh",
            "Y2tEZXNjcmlwdG9ySAASOAoLdHJhY2tfZXZlbnQYCyABKAsyIS51bml0eV9w",
            "ZXJmZXR0by5wcm90b3MuVHJhY2tFdmVudEgAEiQKGnRydXN0ZWRfcGFja2V0",
            "X3NlcXVlbmNlX2lkGAogASgNSAFCBgoEZGF0YUIlCiNvcHRpb25hbF90cnVz",
            "dGVkX3BhY2tldF9zZXF1ZW5jZV9pZEIMCgpfdGltZXN0YW1wYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::UnityPerfetto.Protos.TrackEventReflection.Descriptor, global::UnityPerfetto.Protos.TrackDescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::UnityPerfetto.Protos.TracePacket), global::UnityPerfetto.Protos.TracePacket.Parser, new[]{ "Timestamp", "TrackDescriptor", "TrackEvent", "TrustedPacketSequenceId" }, new[]{ "Data", "OptionalTrustedPacketSequenceId", "Timestamp" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TracePacket : pb::IMessage<TracePacket>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TracePacket> _parser = new pb::MessageParser<TracePacket>(() => new TracePacket());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TracePacket> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UnityPerfetto.Protos.TracePacketReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TracePacket() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TracePacket(TracePacket other) : this() {
      _hasBits0 = other._hasBits0;
      timestamp_ = other.timestamp_;
      switch (other.DataCase) {
        case DataOneofCase.TrackDescriptor:
          TrackDescriptor = other.TrackDescriptor.Clone();
          break;
        case DataOneofCase.TrackEvent:
          TrackEvent = other.TrackEvent.Clone();
          break;
      }

      switch (other.OptionalTrustedPacketSequenceIdCase) {
        case OptionalTrustedPacketSequenceIdOneofCase.TrustedPacketSequenceId:
          TrustedPacketSequenceId = other.TrustedPacketSequenceId;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TracePacket Clone() {
      return new TracePacket(this);
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 8;
    private readonly static ulong TimestampDefaultValue = 0UL;

    private ulong timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Timestamp {
      get { if ((_hasBits0 & 1) != 0) { return timestamp_; } else { return TimestampDefaultValue; } }
      set {
        _hasBits0 |= 1;
        timestamp_ = value;
      }
    }
    /// <summary>Gets whether the "timestamp" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTimestamp {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "timestamp" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTimestamp() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "track_descriptor" field.</summary>
    public const int TrackDescriptorFieldNumber = 60;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::UnityPerfetto.Protos.TrackDescriptor TrackDescriptor {
      get { return dataCase_ == DataOneofCase.TrackDescriptor ? (global::UnityPerfetto.Protos.TrackDescriptor) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.TrackDescriptor;
      }
    }

    /// <summary>Field number for the "track_event" field.</summary>
    public const int TrackEventFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::UnityPerfetto.Protos.TrackEvent TrackEvent {
      get { return dataCase_ == DataOneofCase.TrackEvent ? (global::UnityPerfetto.Protos.TrackEvent) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.TrackEvent;
      }
    }

    /// <summary>Field number for the "trusted_packet_sequence_id" field.</summary>
    public const int TrustedPacketSequenceIdFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TrustedPacketSequenceId {
      get { return HasTrustedPacketSequenceId ? (uint) optionalTrustedPacketSequenceId_ : 0; }
      set {
        optionalTrustedPacketSequenceId_ = value;
        optionalTrustedPacketSequenceIdCase_ = OptionalTrustedPacketSequenceIdOneofCase.TrustedPacketSequenceId;
      }
    }
    /// <summary>Gets whether the "trusted_packet_sequence_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTrustedPacketSequenceId {
      get { return optionalTrustedPacketSequenceIdCase_ == OptionalTrustedPacketSequenceIdOneofCase.TrustedPacketSequenceId; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "trusted_packet_sequence_id" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTrustedPacketSequenceId() {
      if (HasTrustedPacketSequenceId) {
        ClearOptionalTrustedPacketSequenceId();
      }
    }

    private object data_;
    /// <summary>Enum of possible cases for the "data" oneof.</summary>
    public enum DataOneofCase {
      None = 0,
      TrackDescriptor = 60,
      TrackEvent = 11,
    }
    private DataOneofCase dataCase_ = DataOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataOneofCase DataCase {
      get { return dataCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearData() {
      dataCase_ = DataOneofCase.None;
      data_ = null;
    }

    private object optionalTrustedPacketSequenceId_;
    /// <summary>Enum of possible cases for the "optional_trusted_packet_sequence_id" oneof.</summary>
    public enum OptionalTrustedPacketSequenceIdOneofCase {
      None = 0,
      TrustedPacketSequenceId = 10,
    }
    private OptionalTrustedPacketSequenceIdOneofCase optionalTrustedPacketSequenceIdCase_ = OptionalTrustedPacketSequenceIdOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OptionalTrustedPacketSequenceIdOneofCase OptionalTrustedPacketSequenceIdCase {
      get { return optionalTrustedPacketSequenceIdCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOptionalTrustedPacketSequenceId() {
      optionalTrustedPacketSequenceIdCase_ = OptionalTrustedPacketSequenceIdOneofCase.None;
      optionalTrustedPacketSequenceId_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TracePacket);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TracePacket other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Timestamp != other.Timestamp) return false;
      if (!object.Equals(TrackDescriptor, other.TrackDescriptor)) return false;
      if (!object.Equals(TrackEvent, other.TrackEvent)) return false;
      if (TrustedPacketSequenceId != other.TrustedPacketSequenceId) return false;
      if (DataCase != other.DataCase) return false;
      if (OptionalTrustedPacketSequenceIdCase != other.OptionalTrustedPacketSequenceIdCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasTimestamp) hash ^= Timestamp.GetHashCode();
      if (dataCase_ == DataOneofCase.TrackDescriptor) hash ^= TrackDescriptor.GetHashCode();
      if (dataCase_ == DataOneofCase.TrackEvent) hash ^= TrackEvent.GetHashCode();
      if (HasTrustedPacketSequenceId) hash ^= TrustedPacketSequenceId.GetHashCode();
      hash ^= (int) dataCase_;
      hash ^= (int) optionalTrustedPacketSequenceIdCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasTimestamp) {
        output.WriteRawTag(64);
        output.WriteUInt64(Timestamp);
      }
      if (HasTrustedPacketSequenceId) {
        output.WriteRawTag(80);
        output.WriteUInt32(TrustedPacketSequenceId);
      }
      if (dataCase_ == DataOneofCase.TrackEvent) {
        output.WriteRawTag(90);
        output.WriteMessage(TrackEvent);
      }
      if (dataCase_ == DataOneofCase.TrackDescriptor) {
        output.WriteRawTag(226, 3);
        output.WriteMessage(TrackDescriptor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasTimestamp) {
        output.WriteRawTag(64);
        output.WriteUInt64(Timestamp);
      }
      if (HasTrustedPacketSequenceId) {
        output.WriteRawTag(80);
        output.WriteUInt32(TrustedPacketSequenceId);
      }
      if (dataCase_ == DataOneofCase.TrackEvent) {
        output.WriteRawTag(90);
        output.WriteMessage(TrackEvent);
      }
      if (dataCase_ == DataOneofCase.TrackDescriptor) {
        output.WriteRawTag(226, 3);
        output.WriteMessage(TrackDescriptor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasTimestamp) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Timestamp);
      }
      if (dataCase_ == DataOneofCase.TrackDescriptor) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(TrackDescriptor);
      }
      if (dataCase_ == DataOneofCase.TrackEvent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TrackEvent);
      }
      if (HasTrustedPacketSequenceId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TrustedPacketSequenceId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TracePacket other) {
      if (other == null) {
        return;
      }
      if (other.HasTimestamp) {
        Timestamp = other.Timestamp;
      }
      switch (other.DataCase) {
        case DataOneofCase.TrackDescriptor:
          if (TrackDescriptor == null) {
            TrackDescriptor = new global::UnityPerfetto.Protos.TrackDescriptor();
          }
          TrackDescriptor.MergeFrom(other.TrackDescriptor);
          break;
        case DataOneofCase.TrackEvent:
          if (TrackEvent == null) {
            TrackEvent = new global::UnityPerfetto.Protos.TrackEvent();
          }
          TrackEvent.MergeFrom(other.TrackEvent);
          break;
      }

      switch (other.OptionalTrustedPacketSequenceIdCase) {
        case OptionalTrustedPacketSequenceIdOneofCase.TrustedPacketSequenceId:
          TrustedPacketSequenceId = other.TrustedPacketSequenceId;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 64: {
            Timestamp = input.ReadUInt64();
            break;
          }
          case 80: {
            TrustedPacketSequenceId = input.ReadUInt32();
            break;
          }
          case 90: {
            global::UnityPerfetto.Protos.TrackEvent subBuilder = new global::UnityPerfetto.Protos.TrackEvent();
            if (dataCase_ == DataOneofCase.TrackEvent) {
              subBuilder.MergeFrom(TrackEvent);
            }
            input.ReadMessage(subBuilder);
            TrackEvent = subBuilder;
            break;
          }
          case 482: {
            global::UnityPerfetto.Protos.TrackDescriptor subBuilder = new global::UnityPerfetto.Protos.TrackDescriptor();
            if (dataCase_ == DataOneofCase.TrackDescriptor) {
              subBuilder.MergeFrom(TrackDescriptor);
            }
            input.ReadMessage(subBuilder);
            TrackDescriptor = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 64: {
            Timestamp = input.ReadUInt64();
            break;
          }
          case 80: {
            TrustedPacketSequenceId = input.ReadUInt32();
            break;
          }
          case 90: {
            global::UnityPerfetto.Protos.TrackEvent subBuilder = new global::UnityPerfetto.Protos.TrackEvent();
            if (dataCase_ == DataOneofCase.TrackEvent) {
              subBuilder.MergeFrom(TrackEvent);
            }
            input.ReadMessage(subBuilder);
            TrackEvent = subBuilder;
            break;
          }
          case 482: {
            global::UnityPerfetto.Protos.TrackDescriptor subBuilder = new global::UnityPerfetto.Protos.TrackDescriptor();
            if (dataCase_ == DataOneofCase.TrackDescriptor) {
              subBuilder.MergeFrom(TrackDescriptor);
            }
            input.ReadMessage(subBuilder);
            TrackDescriptor = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
